application:
  databaseUsed: MYSQL
  gateway:
    rickAndMortyApi: https://rickandmortyapi.com/api
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rick_and_morty_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: student
    password: student
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rick_and_morty_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect